# Weather forcasts API Calls

In [1]:
import requests
import pandas as pd

In [2]:

city_geolocation_df = pd.read_csv("C:\\Users\\onlyu\\OneDrive\\Coding_Projects\\Fantasy_Football\\data\\nfl_stadium_city_coordinates_2026.csv")
print(city_geolocation_df.dtypes)
city_geolocation_df.head()

city      object
state     object
lat      float64
long     float64
dtype: object

                      city           state        lat        long
0                 Glendale         Arizona  33.538686 -112.185994
1                  Atlanta         Georgia  33.748992  -84.390264
2                Baltimore        Maryland  39.290882  -76.610759
3  Village of Orchard Park        New York  42.767038  -78.743552
4                Charlotte  North Carolina  35.227209  -80.843083

In [3]:

all_stadium_weather = []

API_KEY = "5ecdd6fd1b07f856442a0fb8d19ffbb7"
url = "https://api.open-meteo.com/v1/forecast"

for index, city in city_geolocation_df.iterrows():

    params = {
        "latitude": city["lat"],
        "longitude": city["long"],
        "hourly": "temperature_2m,precipitation_probability,precipitation,wind_speed_10m",
        "forecast_days": 7,
        "timezone": "auto",
        "temperature_unit": "fahrenheit",
        "windspeed_unit": "mph",
        "precipitation_unit": "inch"
    }

    response = requests.get(url, params=params)

    data = response.json()

    print(data)
    all_stadium_weather.append({
        "city": city["city"],
        "state": city["state"],
        "lat": city["lat"],
        "long": city["long"],
        "weather": data,
    })

{'latitude': 33.533676, 'longitude': -112.17606, 'generationtime_ms': 6.651520729064941, 'utc_offset_seconds': -25200, 'timezone': 'America/Phoenix', 'timezone_abbreviation': 'GMT-7', 'elevation': 350.0, 'hourly_units': {'time': 'iso8601', 'temperature_2m': '°F', 'precipitation_probability': '%', 'precipitation': 'inch', 'wind_speed_10m': 'mp/h'}, 'hourly': {'time': ['2026-10-07T00:00', '2026-10-07T01:00', '2026-10-07T02:00', '2026-10-07T03:00', '2026-10-07T04:00', '2026-10-07T05:00', '2026-10-07T06:00', '2026-10-07T07:00', '2026-10-07T08:00', '2026-10-07T09:00', '2026-10-07T10:00', '2026-10-07T11:00', '2026-10-07T12:00', '2026-10-07T13:00', '2026-10-07T14:00', '2026-10-07T15:00', '2026-10-07T16:00', '2026-10-07T17:00', '2026-10-07T18:00', '2026-10-07T19:00', '2026-10-07T20:00', '2026-10-07T21:00', '2026-10-07T22:00', '2026-10-07T23:00', '2026-10-08T00:00', '2026-10-08T01:00', '2026-10-08T02:00', '2026-10-08T03:00', '2026-10-08T04:00', '2026-10-08T05:00', '2026-10-08T06:00', '2026-10-08T07:00', '2026-10-08T08:00', '2026-10-08T09:00', '2026-10-08T10:00', '2026-10-08T11:00', '2026-10-08T12:00', '2026-10-08T13:00', '2026-10-08T14:00', '2026-10-08T15:00', '2026-10-08T16:00', '2026-10-08T17:00', '2026-10-08T18:00', '2026-10-08T19:00', '2026-10-08T20:00', '2026-10-08T21:00', '2026-10-08T22:00', '2026-10-08T23:00', '2026-10-09T00:00', '2026-10-09T01:00', '2026-10-09T02:00', '2026-10-09T03:00', '2026-10-09T04:00', '2026-10-09T05:00', '2026-10-09T06:00', '2026-10-09T07:00', '2026-10-09T08:00', '2026-10-09T09:00', '2026-10-09T10:00', '2026-10-09T11:00', '2026-10-09T12:00', '2026-10-09T13:00', '2026-10-09T14:00', '2026-10-09T15:00', '2026-10-09T16:00', '2026-10-09T17:00', '2026-10-09T18:00', '2026-10-09T19:00', '2026-10-09T20:00', '2026-10-09T21:00', '2026-10-09T22:00', '2026-10-09T23:00', '2026-10-10T00:00', '2026-10-10T01:00', '2026-10-10T02:00', '2026-10-10T03:00', '2026-10-10T04:00', '2026-10-10T05:00', '2026-10-10T06:00', '2026-10-10T07:00', '2026-10-10T08:00', '2026-10-10T09:00', '2026-10-10T10:00', '2026-10-10T11:00', '2026-10-10T12:00', '2026-10-10T13:00', '2026-10-10T14:00', '2026-10-10T15:00', '2026-10-10T16:00', '2026-10-10T17:00', '2026-10-10T18:00', '2026-10-10T19:00', '2026-10-10T20:00', '2026-10-10T21:00', '2026-10-10T22:00', '2026-10-10T23:00', '2026-10-11T00:00', '2026-10-11T01:00', '2026-10-11T02:00', '2026-10-11T03:00', '2026-10-11T04:00', '2026-10-11T05:00', '2026-10-11T06:00', '2026-10-11T07:00', '2026-10-11T08:00', '2026-10-11T09:00', '2026-10-11T10:00', '2026-10-11T11:00', '2026-10-11T12:00', '2026-10-11T13:00', '2026-10-11T14:00', '2026-10-11T15:00', '2026-10-11T16:00', '2026-10-11T17:00', '2026-10-11T18:00', '2026-10-11T19:00', '2026-10-11T20:00', '2026-10-11T21:00', '2026-10-11T22:00', '2026-10-11T23:00', '2026-10-12T00:00', '2026-10-12T01:00', '2026-10-12T02:00', '2026-10-12T03:00', '2026-10-12T04:00', '2026-10-12T05:00', '2026-10-12T06:00', '2026-10-12T07:00', '2026-10-12T08:00', '2026-10-12T09:00', '2026-10-12T10:00', '2026-10-12T11:00', '2026-10-12T12:00', '2026-10-12T13:00', '2026-10-12T14:00', '2026-10-12T15:00', '2026-10-12T16:00', '2026-10-12T17:00', '2026-10-12T18:00', '2026-10-12T19:00', '2026-10-12T20:00', '2026-10-12T21:00', '2026-10-12T22:00', '2026-10-12T23:00', '2026-10-13T00:00', '2026-10-13T01:00', '2026-10-13T02:00', '2026-10-13T03:00', '2026-10-13T04:00', '2026-10-13T05:00', '2026-10-13T06:00', '2026-10-13T07:00', '2026-10-13T08:00', '2026-10-13T09:00', '2026-10-13T10:00', '2026-10-13T11:00', '2026-10-13T12:00', '2026-10-13T13:00', '2026-10-13T14:00', '2026-10-13T15:00', '2026-10-13T16:00', '2026-10-13T17:00', '2026-10-13T18:00', '2026-10-13T19:00', '2026-10-13T20:00', '2026-10-13T21:00', '2026-10-13T22:00', '2026-10-13T23:00'], 'temperature_2m': [83.5, 82.0, 80.8, 79.5, 78.0, 77.8, 77.7, 77.0, 81.0, 86.1, 91.8, 95.3, 97.8, 99.4, 100.3, 100.6, 100.1, 98.9, 94.9, 90.8, 88.1, 86.2, 84.0, 82.4, 82.2, 79.8, 78.1, 77.6, 76.6, 75.4, 74.7, 75.0, 81.3, 88.4, 92.9, 96.9, 99.3, 101.1, 102.1, 102.5, 102.0, 100.4, 95.7, 91.4, 88.4, 86.8, 84.9, 82.3, 81.9, 80.8, 79.9, 81.0, 83.8, 86.6, 89.9, 89.9, 90.0, 90.6, 92.2, 95.1, 96.9, 97.2, 97.1, 99.0, 99.4, 99.4, 98.5, 96.2, 95.6, 95.1, 94.0, 92.7, 91.3, 90.4, 89.5, 89.0, 88.4, 87.3, 85.2, 84.3, 85.7, 85.2, 85.5, 89.3, 91.8, 92.0, 91.8, 92.4, 90.9, 90.9, 89.3, 87.9, 82.7, 81.0, 81.6, 80.9, 79.8, 78.7, 78.1, 77.4, 76.7, 77.1, 77.8, 78.7, 78.9, 79.6, 75.5, 71.5, 72.8, 77.6, 82.1, 85.2, 84.7, 83.7, 81.8, 80.2, 79.1, 77.4, 76.5, 76.0, 75.9, 76.1, 76.2, 75.7, 75.0, 74.6, 74.5, 74.6, 75.3, 76.9, 79.2, 81.0, 82.3, 83.2, 83.9, 84.8, 85.5, 85.5, 84.1, 81.9, 80.1, 79.0, 78.2, 77.5, 76.9, 76.4, 76.0, 75.8, 75.7, 75.8, 76.1, 76.6, 77.3, 78.4, 79.9, 80.3, 79.2, 77.3, 75.5, 74.1, 72.9, 71.9, 71.2, 70.9, 70.7, 70.6, 70.7, 70.9], 'precipitation_probability': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 7, 7, 7, 7, 21, 21, 21, 21, 21, 21, 32, 32, 32, 32, 32, 32, 44, 44, 44, 44, 44, 44, 53, 53, 53, 53, 53, 53, 68, 68, 68, 68, 68, 68, 53, 53, 53, 53, 53, 53, 40, 40, 40, 40, 40, 40, 58, 58, 58, 58, 58, 58, 63, 63, 63, 63, 63, 63, 41, 41, 41, 41, 41, 41, 23, 23, 23, 23, 23, 23, 41, 41, 41, 41, 41, 41, 49, 49, 49, 49, 49, 49, 27, 27, 27, 27, 27, 27, 17, 17, 17, 17, 17, 17], 'precipitation': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.016, 0.024, 0.0, 0.028, 0.008, 0.0, 0.0, 0.004, 0.004, 0.004, 0.024, 0.004, 0.004, 0.008, 0.024, 0.039, 0.016, 0.008, 0.024, 0.016, 0.004, 0.028, 0.047, 0.024, 0.024, 0.012, 0.031, 0.063, 0.102, 0.177, 0.165, 0.008, 0.004, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.004, 0.004, 0.004, 0.0, 0.0, 0.0, 0.004, 0.004, 0.004, 0.008, 0.008, 0.008, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.012, 0.012, 0.012, 0.024, 0.024, 0.024, 0.012, 0.012, 0.012], 'wind_speed_10m': [3.6, 3.1, 3.1, 2.7, 3.9, 1.0, 2.9, 2.1, 1.1, 2.4, 3.5, 2.9, 1.4, 0.4, 1.6, 3.1, 5.1, 4.3, 4.5, 5.0, 4.7, 4.2, 4.7, 4.0, 3.1, 1.8, 3.0, 5.2, 4.7, 5.0, 5.0, 5.1, 4.5, 6.5, 6.3, 5.9, 5.4, 2.4, 0.9, 2.1, 5.0, 4.4, 2.7, 4.6, 2.8, 4.5, 4.1, 5.4, 4.7, 5.8, 2.4, 4.1, 4.7, 4.1, 4.0, 4.3, 5.6, 6.7, 8.0, 9.0, 10.2, 10.4, 9.9, 8.4, 9.5, 10.2, 11.1, 13.7, 10.5, 9.7, 7.2, 6.8, 3.8, 2.1, 2.6, 0.8, 1.5, 3.5, 1.6, 5.8, 9.1, 2.9, 5.2, 6.5, 6.8, 6.0, 6.2, 2.8, 2.7, 4.3, 4.7, 10.5, 9.8, 2.6, 7.6, 9.0, 10.6, 12.9, 12.3, 10.9, 8.9, 9.4, 7.1, 7.2, 8.4, 13.3, 16.0, 19.0, 15.0, 13.6, 16.8, 21.3, 21.4, 19.6, 16.3, 14.6, 14.7, 13.1, 10.7, 8.8, 6.8, 7.1, 8.6, 9.4, 9.5, 9.4, 8.7, 7.8, 7.0, 6.6, 7.2, 8.3, 8.7, 9.3, 10.0, 11.0, 12.0, 12.2, 11.3, 12.7, 14.5, 13.7, 11.1, 8.4, 6.3, 4.3, 2.5, 1.2, 0.2, 0.4, 1.2, 1.9, 3.3, 5.5, 8.0, 10.0, 11.7, 12.8, 13.5, 13.7, 13.3, 12.7, 11.4, 9.6, 8.2, 7.8, 7.6, 7.1]}}
{'latitude': 33.759865, 'longitude': -84.39586, 'generationtime_ms': 0.21755695343017578, 'utc_offset_seconds': -14400, 'timezone': 'America/New_York', 'timezone_abbreviation': 'GMT-4', 'elevation': 317.0, 'hourly_units': {'time': 'iso8601', 'temperature_2m': '°F', 'precipitation_probability': '%', 'precipitation': 'inch', 'wind_speed_10m': 'mp/h'}, 'hourly': {'time': ['2026-10-07T00:00', '2026-10-07T01:00', '2026-10-07T02:00', '2026-10-07T03:00', '2026-10-07T04:00', '2026-10-07T05:00', '2026-10-07T06:00', '2026-10-07T07:00', '2026-10-07T08:00', '2026-10-07T09:00', '2026-10-07T10:00', '2026-10-07T11:00', '2026-10-07T12:00', '2026-10-07T13:00', '2026-10-07T14:00', '2026-10-07T15:00', '2026-10-07T16:00', '2026-10-07T17:00', '2026-10-07T18:00', '2026-10-07T19:00', '2026-10-07T20:00', '2026-10-07T21:00', '2026-10-07T22:00', '2026-10-07T23:00', '2026-10-08T00:00', '2026-10-08T01:00', '2026-10-08T02:00', '2026-10-08T03:00', '2026-10-08T04:00', '2026-10-08T05:00', '2026-10-08T06:00', '2026-10-08T07:00', '2026-10-08T08:00', '2026-10-08T09:00', '2026-10-08T10:00', '2026-10-08T11:00', '2026-10-08T12:00', '2026-10-08T13:00', '2026-10-08T14:00', '2026-10-08T15:00', '2026-10-08T16:00', '2026-10-08T17:00', '2026-10-08T18:00', '2026-10-08T19:00', '2026-10-08T20:00', '2026-10-08T21:00', '2026-10-08T22:00', '2026-10-08T23:00', '2026-10-09T00:00', '2026-10-09T01:00', '2026-10-09T02:00', '2026-10-09T03:00', '2026-10-09T04:00', '2026-10-09T05:00', '2026-10-09T06:00', '2026-10-09T07:00', '2026-10-09T08:00', '2026-10-09T09:00', '2026-10-09T10:00', '2026-10-09T11:00', '2026-10-09T12:00', '2026-10-09T13:00', '2026-10-09T14:00', '2026-10-09T15:00', '2026-10-09T16:00', '2026-10-09T17:00', '2026-10-09T18:00', '2026-10-09T19:00', '2026-10-09T20:00', '2026-10-09T21:00', '2026-10-09T22:00', '2026-10-09T23:00', '2026-10-10T00:00', '2026-10-10T01:00', '2026-10-10T02:00', '2026-10-10T03:00', '2026-10-10T04:00', '2026-10-10T05:00', '2026-10-10T06:00', '2026-10-10T07:00', '2026-10-10T08:00', '2026-10-10T09:00', '2026-10-10T10:00', '2026-10-10T11:00', '2026-10-10T12:00', '2026-10-10T13:00', '2026-10-10T14:00', '2026-10-10T15:00', '2026-10-10T16:00', '2026-10-10T17:00', '2026-10-10T18:00', '2026-10-10T19:00', '2026-10-10T20:00', '2026-10-10T21:00', '2026-10-10T22:00', '2026-10-10T23:00', '2026-10-11T00:00', '2026-10-11T01:00', '2026-10-11T02:00', '2026-10-11T03:00', '2026-10-11T04:00', '2026-10-11T05:00', '2026-10-11T06:00', '2026-10-11T07:00', '2026-10-11T08:00', '2026-10-11T09:00', '2026-10-11T10:00', '2026-10-11T11:00', '2026-10-11T12:00', '2026-10-11T13:00', '2026-10-11T14:00', '2026-10-11T15:00', '2026-10-11T16:00', '2026-10-11T17:00', '2026-10-11T18:00', '2026-10-11T19:00', '2026-10-11T20:00', '2026-10-11T21:00', '2026-10-11T22:00', '2026-10-11T23:00', '2026-10-12T00:00', '2026-10-12T01:00', '2026-10-12T02:00', '2026-10-12T03:00', '2026-10-12T04:00', '2026-10-12T05:00', '2026-10-12T06:00', '2026-10-12T07:00', '2026-10-12T08:00', '2026-10-12T09:00', '2026-10-12T10:00', '2026-10-12T11:00', '2026-10-12T12:00', '2026-10-12T13:00', '2026-10-12T14:00', '2026-10-12T15:00', '2026-10-12T16:00', '2026-10-12T17:00', '2026-10-12T18:00', '2026-10-12T19:00', '2026-10-12T20:00', '2026-10-12T21:00', '2026-10-12T22:00', '2026-10-12T23:00', '2026-10-13T00:00', '2026-10-13T01:00', '2026-10-13T02:00', '2026-10-13T03:00', '2026-10-13T04:00', '2026-10-13T05:00', '2026-10-13T06:00', '2026-10-13T07:00', '2026-10-13T08:00', '2026-10-13T09:00', '2026-10-13T10:00', '2026-10-13T11:00', '2026-10-13T12:00', '2026-10-13T13:00', '2026-10-13T14:00', '2026-10-13T15:00', '2026-10-13T16:00', '2026-10-13T17:00', '2026-10-13T18:00', '2026-10-13T19:00', '2026-10-13T20:00', '2026-10-13T21:00', '2026-10-13T22:00', '2026-10-13T23:00'], 'temperature_2m': [63.4, 60.7, 59.8, 59.1, 58.5, 57.8, 56.8, 56.1, 55.7, 60.8, 64.9, 69.2, 72.6, 75.5, 77.8, 79.5, 80.5, 80.5, 79.5, 75.4, 71.1, 68.5, 67.3, 66.7, 66.0, 64.9, 63.6, 62.5, 61.4, 60.0, 59.1, 57.8, 57.4, 62.2, 70.0, 75.6, 79.6, 82.1, 83.7, 84.9, 85.9, 85.7, 85.0, 80.5, 77.2, 73.3, 71.5, 70.5, 68.9, 67.9, 66.1, 65.3, 63.7, 62.4, 63.2, 65.0, 66.5, 68.3, 69.0, 70.5, 71.7, 73.0, 74.3, 74.4, 74.6, 73.2, 71.4, 69.6, 67.8, 65.8, 63.1, 62.7, 61.5, 60.8, 60.2, 58.6, 58.6, 59.1, 59.3, 59.0, 58.6, 58.4, 58.8, 59.0, 59.0, 59.3, 59.5, 60.0, 60.8, 61.5, 61.7, 62.0, 62.2, 62.6, 62.9, 63.5, 63.8, 64.2, 64.5, 65.3, 66.6, 66.9, 67.6, 67.6, 67.2, 67.2, 67.6, 68.9, 72.1, 74.6, 76.2, 76.2, 77.5, 77.3, 76.1, 73.4, 71.7, 70.5, 69.2, 68.1, 67.1, 66.1, 65.4, 64.7, 64.1, 63.6, 62.7, 61.9, 62.6, 65.7, 70.3, 74.4, 77.7, 80.6, 82.5, 83.6, 83.9, 83.3, 81.1, 78.0, 75.4, 73.9, 72.8, 71.7, 70.7, 69.6, 68.6, 67.8, 67.0, 66.3, 65.3, 64.4, 64.9, 68.1, 72.7, 77.0, 80.2, 83.0, 84.9, 85.9, 86.0, 85.2, 83.2, 80.2, 77.7, 76.1, 74.8, 73.7], 'precipitation_probability': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 21, 21, 21, 21, 21, 21, 52, 52, 52, 52, 52, 52, 66, 66, 66, 66, 66, 66, 87, 87, 87, 87, 87, 87, 79, 79, 79, 79, 79, 79, 63, 63, 63, 63, 63, 63, 50, 50, 50, 50, 50, 50, 32, 32, 32, 32, 32, 32, 11, 11, 11, 11, 11, 11, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'precipitation': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.02, 0.028, 0.083, 0.091, 0.059, 0.067, 0.083, 0.209, 0.283, 0.224, 0.102, 0.126, 0.083, 0.205, 0.102, 0.043, 0.02, 0.008, 0.004, 0.004, 0.016, 0.02, 0.012, 0.024, 0.016, 0.043, 0.008, 0.016, 0.016, 0.012, 0.016, 0.031, 0.004, 0.0, 0.0, 0.004, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'wind_speed_10m': [4.0, 3.2, 2.6, 2.9, 2.9, 3.6, 2.9, 2.9, 3.5, 5.5, 6.7, 6.5, 4.6, 3.8, 3.4, 3.1, 2.9, 2.3, 2.4, 4.3, 4.3, 4.2, 1.9, 3.2, 1.4, 1.1, 0.8, 1.3, 0.9, 1.4, 1.9, 1.4, 2.8, 1.7, 4.6, 5.2, 6.2, 6.6, 6.0, 6.1, 4.3, 4.4, 4.7, 3.0, 4.2, 4.3, 3.5, 2.8, 4.0, 3.8, 4.8, 2.4, 2.6, 5.4, 5.2, 6.8, 7.7, 8.6, 9.9, 10.5, 11.0, 9.9, 10.6, 11.0, 10.1, 10.0, 10.3, 12.0, 11.9, 12.8, 11.9, 13.3, 13.0, 17.6, 16.1, 16.0, 18.0, 18.6, 20.5, 21.8, 21.8, 20.8, 20.2, 19.9, 18.1, 18.6, 17.5, 17.1, 16.6, 16.4, 15.5, 14.6, 13.9, 13.1, 11.5, 9.9, 8.1, 7.5, 8.2, 6.0, 5.0, 5.4, 6.0, 6.0, 6.8, 8.5, 10.1, 10.8, 11.7, 12.4, 13.5, 13.2, 12.7, 12.6, 10.3, 9.7, 8.2, 7.5, 7.0, 6.3, 6.0, 5.8, 5.8, 5.9, 6.1, 6.3, 6.3, 6.3, 6.4, 7.0, 7.8, 8.5, 9.2, 9.6, 9.9, 9.8, 9.4, 8.6, 6.9, 5.0, 3.5, 3.3, 3.6, 4.3, 4.5, 4.7, 4.8, 4.8, 4.7, 4.7, 4.8, 4.9, 5.1, 5.7, 6.3, 6.8, 7.0, 7.2, 7.3, 8.0, 8.6, 8.6, 7.5, 5.7, 4.6, 4.6, 5.2, 5.7]}}

In [5]:
print(all_stadium_weather[0])

{'city': 'Glendale', 'state': 'Arizona', 'lat': 33.5386858, 'long': -112.185994, 'weather': {'latitude': 33.533676, 'longitude': -112.17606, 'generationtime_ms': 6.651520729064941, 'utc_offset_seconds': -25200, 'timezone': 'America/Phoenix', 'timezone_abbreviation': 'GMT-7', 'elevation': 350.0, 'hourly_units': {'time': 'iso8601', 'temperature_2m': '°F', 'precipitation_probability': '%', 'precipitation': 'inch', 'wind_speed_10m': 'mp/h'}, 'hourly': {'time': ['2026-10-07T00:00', '2026-10-07T01:00', '2026-10-07T02:00', '2026-10-07T03:00', '2026-10-07T04:00', '2026-10-07T05:00', '2026-10-07T06:00', '2026-10-07T07:00', '2026-10-07T08:00', '2026-10-07T09:00', '2026-10-07T10:00', '2026-10-07T11:00', '2026-10-07T12:00', '2026-10-07T13:00', '2026-10-07T14:00', '2026-10-07T15:00', '2026-10-07T16:00', '2026-10-07T17:00', '2026-10-07T18:00', '2026-10-07T19:00', '2026-10-07T20:00', '2026-10-07T21:00', '2026-10-07T22:00', '2026-10-07T23:00', '2026-10-08T00:00', '2026-10-08T01:00', '2026-10-08T02:00', '2026-10-08T03:00', '2026-10-08T04:00', '2026-10-08T05:00', '2026-10-08T06:00', '2026-10-08T07:00', '2026-10-08T08:00', '2026-10-08T09:00', '2026-10-08T10:00', '2026-10-08T11:00', '2026-10-08T12:00', '2026-10-08T13:00', '2026-10-08T14:00', '2026-10-08T15:00', '2026-10-08T16:00', '2026-10-08T17:00', '2026-10-08T18:00', '2026-10-08T19:00', '2026-10-08T20:00', '2026-10-08T21:00', '2026-10-08T22:00', '2026-10-08T23:00', '2026-10-09T00:00', '2026-10-09T01:00', '2026-10-09T02:00', '2026-10-09T03:00', '2026-10-09T04:00', '2026-10-09T05:00', '2026-10-09T06:00', '2026-10-09T07:00', '2026-10-09T08:00', '2026-10-09T09:00', '2026-10-09T10:00', '2026-10-09T11:00', '2026-10-09T12:00', '2026-10-09T13:00', '2026-10-09T14:00', '2026-10-09T15:00', '2026-10-09T16:00', '2026-10-09T17:00', '2026-10-09T18:00', '2026-10-09T19:00', '2026-10-09T20:00', '2026-10-09T21:00', '2026-10-09T22:00', '2026-10-09T23:00', '2026-10-10T00:00', '2026-10-10T01:00', '2026-10-10T02:00', '2026-10-10T03:00', '2026-10-10T04:00', '2026-10-10T05:00', '2026-10-10T06:00', '2026-10-10T07:00', '2026-10-10T08:00', '2026-10-10T09:00', '2026-10-10T10:00', '2026-10-10T11:00', '2026-10-10T12:00', '2026-10-10T13:00', '2026-10-10T14:00', '2026-10-10T15:00', '2026-10-10T16:00', '2026-10-10T17:00', '2026-10-10T18:00', '2026-10-10T19:00', '2026-10-10T20:00', '2026-10-10T21:00', '2026-10-10T22:00', '2026-10-10T23:00', '2026-10-11T00:00', '2026-10-11T01:00', '2026-10-11T02:00', '2026-10-11T03:00', '2026-10-11T04:00', '2026-10-11T05:00', '2026-10-11T06:00', '2026-10-11T07:00', '2026-10-11T08:00', '2026-10-11T09:00', '2026-10-11T10:00', '2026-10-11T11:00', '2026-10-11T12:00', '2026-10-11T13:00', '2026-10-11T14:00', '2026-10-11T15:00', '2026-10-11T16:00', '2026-10-11T17:00', '2026-10-11T18:00', '2026-10-11T19:00', '2026-10-11T20:00', '2026-10-11T21:00', '2026-10-11T22:00', '2026-10-11T23:00', '2026-10-12T00:00', '2026-10-12T01:00', '2026-10-12T02:00', '2026-10-12T03:00', '2026-10-12T04:00', '2026-10-12T05:00', '2026-10-12T06:00', '2026-10-12T07:00', '2026-10-12T08:00', '2026-10-12T09:00', '2026-10-12T10:00', '2026-10-12T11:00', '2026-10-12T12:00', '2026-10-12T13:00', '2026-10-12T14:00', '2026-10-12T15:00', '2026-10-12T16:00', '2026-10-12T17:00', '2026-10-12T18:00', '2026-10-12T19:00', '2026-10-12T20:00', '2026-10-12T21:00', '2026-10-12T22:00', '2026-10-12T23:00', '2026-10-13T00:00', '2026-10-13T01:00', '2026-10-13T02:00', '2026-10-13T03:00', '2026-10-13T04:00', '2026-10-13T05:00', '2026-10-13T06:00', '2026-10-13T07:00', '2026-10-13T08:00', '2026-10-13T09:00', '2026-10-13T10:00', '2026-10-13T11:00', '2026-10-13T12:00', '2026-10-13T13:00', '2026-10-13T14:00', '2026-10-13T15:00', '2026-10-13T16:00', '2026-10-13T17:00', '2026-10-13T18:00', '2026-10-13T19:00', '2026-10-13T20:00', '2026-10-13T21:00', '2026-10-13T22:00', '2026-10-13T23:00'], 'temperature_2m': [83.5, 82.0, 80.8, 79.5, 78.0, 77.8, 77.7, 77.0, 81.0, 86.1, 91.8, 95.3, 97.8, 99.4, 100.3, 100.6, 100.1, 98.9, 94.9, 90.8, 88.1, 86.2, 84.0, 82.4, 82.2, 79.8, 78.1, 77.6, 76.6, 75.4, 74.7, 75.0, 81.3, 88.4, 92.9, 96.9, 99.3, 101.1, 102.1, 102.5, 102.0, 100.4, 95.7, 91.4, 88.4, 86.8, 84.9, 82.3, 81.9, 80.8, 79.9, 81.0, 83.8, 86.6, 89.9, 89.9, 90.0, 90.6, 92.2, 95.1, 96.9, 97.2, 97.1, 99.0, 99.4, 99.4, 98.5, 96.2, 95.6, 95.1, 94.0, 92.7, 91.3, 90.4, 89.5, 89.0, 88.4, 87.3, 85.2, 84.3, 85.7, 85.2, 85.5, 89.3, 91.8, 92.0, 91.8, 92.4, 90.9, 90.9, 89.3, 87.9, 82.7, 81.0, 81.6, 80.9, 79.8, 78.7, 78.1, 77.4, 76.7, 77.1, 77.8, 78.7, 78.9, 79.6, 75.5, 71.5, 72.8, 77.6, 82.1, 85.2, 84.7, 83.7, 81.8, 80.2, 79.1, 77.4, 76.5, 76.0, 75.9, 76.1, 76.2, 75.7, 75.0, 74.6, 74.5, 74.6, 75.3, 76.9, 79.2, 81.0, 82.3, 83.2, 83.9, 84.8, 85.5, 85.5, 84.1, 81.9, 80.1, 79.0, 78.2, 77.5, 76.9, 76.4, 76.0, 75.8, 75.7, 75.8, 76.1, 76.6, 77.3, 78.4, 79.9, 80.3, 79.2, 77.3, 75.5, 74.1, 72.9, 71.9, 71.2, 70.9, 70.7, 70.6, 70.7, 70.9], 'precipitation_probability': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 7, 7, 7, 7, 21, 21, 21, 21, 21, 21, 32, 32, 32, 32, 32, 32, 44, 44, 44, 44, 44, 44, 53, 53, 53, 53, 53, 53, 68, 68, 68, 68, 68, 68, 53, 53, 53, 53, 53, 53, 40, 40, 40, 40, 40, 40, 58, 58, 58, 58, 58, 58, 63, 63, 63, 63, 63, 63, 41, 41, 41, 41, 41, 41, 23, 23, 23, 23, 23, 23, 41, 41, 41, 41, 41, 41, 49, 49, 49, 49, 49, 49, 27, 27, 27, 27, 27, 27, 17, 17, 17, 17, 17, 17], 'precipitation': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.016, 0.024, 0.0, 0.028, 0.008, 0.0, 0.0, 0.004, 0.004, 0.004, 0.024, 0.004, 0.004, 0.008, 0.024, 0.039, 0.016, 0.008, 0.024, 0.016, 0.004, 0.028, 0.047, 0.024, 0.024, 0.012, 0.031, 0.063, 0.102, 0.177, 0.165, 0.008, 0.004, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.004, 0.004, 0.004, 0.0, 0.0, 0.0, 0.004, 0.004, 0.004, 0.008, 0.008, 0.008, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.012, 0.012, 0.012, 0.024, 0.024, 0.024, 0.012, 0.012, 0.012], 'wind_speed_10m': [3.6, 3.1, 3.1, 2.7, 3.9, 1.0, 2.9, 2.1, 1.1, 2.4, 3.5, 2.9, 1.4, 0.4, 1.6, 3.1, 5.1, 4.3, 4.5, 5.0, 4.7, 4.2, 4.7, 4.0, 3.1, 1.8, 3.0, 5.2, 4.7, 5.0, 5.0, 5.1, 4.5, 6.5, 6.3, 5.9, 5.4, 2.4, 0.9, 2.1, 5.0, 4.4, 2.7, 4.6, 2.8, 4.5, 4.1, 5.4, 4.7, 5.8, 2.4, 4.1, 4.7, 4.1, 4.0, 4.3, 5.6, 6.7, 8.0, 9.0, 10.2, 10.4, 9.9, 8.4, 9.5, 10.2, 11.1, 13.7, 10.5, 9.7, 7.2, 6.8, 3.8, 2.1, 2.6, 0.8, 1.5, 3.5, 1.6, 5.8, 9.1, 2.9, 5.2, 6.5, 6.8, 6.0, 6.2, 2.8, 2.7, 4.3, 4.7, 10.5, 9.8, 2.6, 7.6, 9.0, 10.6, 12.9, 12.3, 10.9, 8.9, 9.4, 7.1, 7.2, 8.4, 13.3, 16.0, 19.0, 15.0, 13.6, 16.8, 21.3, 21.4, 19.6, 16.3, 14.6, 14.7, 13.1, 10.7, 8.8, 6.8, 7.1, 8.6, 9.4, 9.5, 9.4, 8.7, 7.8, 7.0, 6.6, 7.2, 8.3, 8.7, 9.3, 10.0, 11.0, 12.0, 12.2, 11.3, 12.7, 14.5, 13.7, 11.1, 8.4, 6.3, 4.3, 2.5, 1.2, 0.2, 0.4, 1.2, 1.9, 3.3, 5.5, 8.0, 10.0, 11.7, 12.8, 13.5, 13.7, 13.3, 12.7, 11.4, 9.6, 8.2, 7.8, 7.6, 7.1]}}}

In [24]:
dfs = []

for data in all_stadium_weather:
    df = pd.DataFrame(data["weather"]['hourly'])
    
    df["city"] = data['city']
    df["state"] = data['state']
    df["latitude"] = data["lat"]
    df["longitude"] = data["long"]
    
    #for each in data["weather"]:
    #    df = pd.DataFrame(data["hourly"])
    
    dfs.append(df)

weather_df = pd.concat(dfs, ignore_index=True)

weather_df.head()

,time,temperature_2m,precipitation_probability,precipitation,wind_speed_10m,city,state,latitude,longitude
0,2026-10-07T00:00,83.5,0,0.0,3.6,Glendale,Arizona,33.538686,-112.185994
1,2026-10-07T01:00,82.0,0,0.0,3.1,Glendale,Arizona,33.538686,-112.185994
2,2026-10-07T02:00,80.8,0,0.0,3.1,Glendale,Arizona,33.538686,-112.185994
3,2026-10-07T03:00,79.5,0,0.0,2.7,Glendale,Arizona,33.538686,-112.185994
4,2026-10-07T04:00,78.0,0,0.0,3.9,Glendale,Arizona,33.538686,-112.185994

In [21]:
from datetime import datetime

today = datetime.today()
today = today.strftime("%Y-%m-%d-%H-%M-%S")

weather_df.to_csv(f"C:\\Users\\onlyu\\OneDrive\\Coding_Projects\\Fantasy_Football\\data\\nfl_stadium_weather_{today}.csv", index=False)

In [25]:
weather_df['time'] = pd.to_datetime(weather_df['time'])
#weather_df['time'] = weather_df['time'].dt.strftime("%H-%M-%S")
#weather_df['date'] = weather_df['time'].dt.date

weather_df.head()

,time,temperature_2m,precipitation_probability,precipitation,wind_speed_10m,city,state,latitude,longitude
0,2026-10-07 00:00:00,83.5,0,0.0,3.6,Glendale,Arizona,33.538686,-112.185994
1,2026-10-07 01:00:00,82.0,0,0.0,3.1,Glendale,Arizona,33.538686,-112.185994
2,2026-10-07 02:00:00,80.8,0,0.0,3.1,Glendale,Arizona,33.538686,-112.185994
3,2026-10-07 03:00:00,79.5,0,0.0,2.7,Glendale,Arizona,33.538686,-112.185994
4,2026-10-07 04:00:00,78.0,0,0.0,3.9,Glendale,Arizona,33.538686,-112.185994

In [26]:
weather_df['date'] = pd.to_datetime(weather_df['time']).dt.date
weather_df['time'] = weather_df['time'].dt.strftime("%H-%M-%S")

weather_df.head()

,time,temperature_2m,precipitation_probability,precipitation,wind_speed_10m,city,state,latitude,longitude,date
0,00-00-00,83.5,0,0.0,3.6,Glendale,Arizona,33.538686,-112.185994,2026-10-07
1,01-00-00,82.0,0,0.0,3.1,Glendale,Arizona,33.538686,-112.185994,2026-10-07
2,02-00-00,80.8,0,0.0,3.1,Glendale,Arizona,33.538686,-112.185994,2026-10-07
3,03-00-00,79.5,0,0.0,2.7,Glendale,Arizona,33.538686,-112.185994,2026-10-07
4,04-00-00,78.0,0,0.0,3.9,Glendale,Arizona,33.538686,-112.185994,2026-10-07